services:
  api:
    environment:
      NODE_ENV: development             
    ports:
      - "3000:3000"                
      - "9229:9229"                
    volumes:
      - ../services/api:/app                  
      - /app/node_modules         
    command: ["node", "--watch", "--inspect=0.0.0.0:9229", "server.js"]

  worker:
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"                
      - "9230:9229"
    networks:
      - redis-network
      - dev-network
    volumes:
      - ../services/worker:/app     
      - /app/node_modules          
    command: ["node", "--watch", "--inspect=0.0.0.0:9229", "server.js"]

networks:
  dev-network: